#!/usr/bin/env bash
# Installing and configuring HAProxy on our load balancer
sudo apt-get -y update
sudo apt-get -y install software-properties-common
sudo apt-add-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy=1.8\*
sudo sed -i "$ a\listen 231-lb-01" /etc/haproxy/haproxy.cfg
sudo sed -i "$ a\ \tbind 0.0.0.0:80" /etc/haproxy/haproxy.cfg
sudo sed -i "$ a\ \tmode http" /etc/haproxy/haproxy.cfg
sudo sed -i "$ a\ \tstats enable" /etc/haproxy/haproxy.cfg
sudo sed -i "$ a\ \tstats uri /haproxy?stats" /etc/haproxy/haproxy.cfg
sudo sed -i "$ a\ \tbalance roundrobin" /etc/haproxy/haproxy.cfg
sudo sed -i "$ a\ \toption httpclose" /etc/haproxy/haproxy.cfg
sudo sed -i "$ a\ \toption forwardfor" /etc/haproxy/haproxy.cfg
sudo sed -i "$ a\ \tserver 231-web-01 54.173.117.136:80 check" /etc/haproxy/haproxy.cfg
sudo sed -i "$ a\ \tserver 231-web-02 52.90.147.235:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
