#!/usr/bin/env bash
# Create a file, display a message indefinitely, display a message when receiving
# a SIGTERM signal, display a message when receiving a SIGINT signal,
# delete the file and terminate itself when receiving a SIGQUIT or SIGTERM signal

echo $$ > holbertonscript.pid
sudo mv holbertonscript.pid /var/run/holbertonscript.pid
trap "echo Y U no love me?!" SIGINT
trap "echo I hate the kill command;
      sudo rm /var/run/holbertonscript.pid; exit" SIGTERM
trap "sudo rm /var/run/holbertonscript.pid; exit" SIGQUIT
while :
do
	echo "To infinity and beyond"
done
