#!/usr/bin/env bash
# Bash script that prints a message indefinitely and prints another message when receiving a SIGTERM signal

trap 'echo "I am invincible!!!"' SIGTERM
while :
do
	echo "To infinity and beyond"
	sleep 2
done
