#!/usr/bin/env bash
# Looping 10 times and printing a string with a different string printing on the 9th iteration
i="0"
while [ $i -lt 10 ]
do
    if [ $i -eq 9 ]
        then
            echo "Hi"
    fi
    i=$((i + 1))
    echo "Holberton School"
done
