#!/usr/bin/env bash
# Looping 20 times and using if/elif/else tree
i="1"
while [ $i -lt 21 ]
do
	echo "$i"
	case $n in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	i=$((i + 1))
done
