#!/usr/bin/env bash
# Printing hours and minutes from hour 0 to 12 and minute 1 to 59
hour="0"
while [ $hour -lt 13 ]
do
	echo "Hour: $hour"
	minute="1"
	while [ $minute -lt 60 ]
	do
		echo "$minute"
		minute=$((minute + 1))
	done
	hour=$((hour + 1))
done
