#!/usr/bin/env bash
#Setting up redirect
sudo apt-get -y install nginx
redirect="54.173.117.136;\n\tlocation \/redirect_me{\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;}"
sed -i "s/localhost;/$redirect/" /etc/nginx/sites-available/default
sudo service nginx restart
